""" 
  @file: compose-dev.yml
  @description: Development compose file for configuring Kubernetes for deployment.
  @author: KeepId Inc.
"""
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: user-response-load-balancer
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 80
#  selector:
#    app:
---
apiVersion: v1
kind: pod
metadata:
  name:
spec:
  selector:
    matchLabels:
      app:
  replicas: 2
  template:
    metadata:
      labels:
        app:
    spec:
      containers:
        - name:
          image: image_database:latest
          ports:
            - containerPort: 80
---
