---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-slow-storage
provisioner: kubernetes.io/no-provisioner # TODO: specify remote volume provisioner
parameters:
  type: pd-standard # Disk-like storage. Can be switched to 'pd-ssd' for faster SSD-like persistent storage.
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim # 'Claim' meaning that it contacts a storage provider for an instance.
metadata:
  name: slow-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-slow-storage
  resources:
    requests:
      storage: 1G1 # How much storage to request
